<?php

	/**
	 * Constants.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     http://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0, 26 Jul 2016
	 */
 
	define("ACTIVATOR_PACKAGE", "lib/getz/Activator.php");	 	 
	define("API", "api");			
	define("APPLICATION_SETTINGS", "settings.xml");		 
	define("ASC", "ASC");	
	define("AUTHORIZATION", "Authorization");	
	define("BACKSLASH", "\\");	
	define("BAD_REQUEST", "Bad request!");		
	define("BAR", "/");
	define("BASE_LINK", "https://@_YOUR_PROJECT.com.br");  // Insert your project name here.
	define("BETWEEN", "BETWEEN");
	define("BRAZILIAN_TIME_ZONE", 3);
	define("COMMA", ",");		
	define("CONTROLLER_PACKAGE", "src/controller/");	
	define("CREATE", "create");		
	define("DATA_NOT_FOUND", "Data not found!");		
	define("DEFAULT_DATE", "1900-01-01 00:00:00");	
	define("DELETE", "delete");		
	define("DESC", "DESC");	
	define("DOC", "doc");
	define("DOCUMENT_ROOT", "DOCUMENT_ROOT");
	define("DOCX", "docx");
	define("DOT", ".");
	define("DOUBLE_QUOTES", "\"");
	define("EQUALS", "=");
	define("FILTER_COLUMN", "filterColumn");	
	define("FILTER_CONDITION", "filterCondition");		
	define("FILTER_VALUE", "filterValue");
	define("FROM", "FROM");	
	define("G3TZ", "g3tz");
	define("GATEWAY_TIMEOUT", "Gateway Timeout!");
	define("GET", "get");
	define("HDPI", "hdpi");
	define("IMAGE", "image");
	define("IMG", "img");
	define("IN", "in");
	define("INSERT", "INSERT");
	define("INTO", "INTO");
	define("IS_REQUIRED", " is required!");
	define("HTML", "html");
	define("HYPHEN", "-");
	define("ID", "id");
	define("INTERNAL_SERVER_ERROR", "Internal server error!");
	define("JPEG", "jpeg");
	define("JPG", "jpg");
	define("LDPI", "ldpi");
	define("LEFT_PARENTHESES", "(");	
	define("LESS_EQUALS", "<=");
	define("LESS_THAN", "<");
	define("LIKE", "LIKE");
	define("LIMIT", "LIMIT");
	define("LOCATION", "Location:");
	define("MDPI", "mdpi");
	define("MESSAGE", "message");		
	define("MODULE_SETTINGS", "settings.xml");
	define("MORE", "+");	
	define("MORE_EQUALS", ">=");		
	define("MORE_ONE_DAYS", "+1 days");		
	define("MORE_THAN", ">");
	define("MORE_THREE_HUNDRED_SIXTY_FIVE", "+365 days");
	define("NOT_EQUALS", "<>");
	define("NOT_FOUND", "not_found");	
	define("NOT_IMPLEMENTED", "Not Implemented!");
	define("NOT_IN", "not in");
	define("NUMBER_FIVE", 5);
	define("NUMBER_FIVE_HUNDRED", 500);		
	define("NUMBER_FIVE_HUNDRED_AND_ONE", 501);	
	define("NUMBER_FIVE_HUNDRED_AND_TWO", 502);	
	define("NUMBER_FIVE_HUNDRED_AND_THREE", 503);	
	define("NUMBER_FIVE_HUNDRED_AND_FOUR", 504);	
	define("NUMBER_FIVE_HUNDRED_AND_FIVE", 505);	
	define("NUMBER_FOUR_HUNDRED", 400);
	define("NUMBER_NINE", 9);
	define("NUMBER_ONE", 1);	
	define("NUMBER_ONE_HUNDRED_TWENTY_EIGHT", 128);
	define("NUMBER_ONE_THOUSAND_TWENTY_FOUR", 1024);	
	define("NUMBER_TEN", 10);	
	define("NUMBER_THIRTY_TWO", 32);
	define("NUMBER_TWO", 2);
	define("NUMBER_TWO_HUNDRED", 200);		
	define("NUMBER_ZERO", 0);
	define("ONE_HOUR_IN_SECONDS", 3600);
	define("ORDER_BY", "ORDER BY");	
	define("ORDER_COLUMN", "orderColumn");	
	define("ORDER_VALUE", "orderValue");		
	define("PAGE", "page");	
	define("PAGE_SIZE", "pageSize");
	define("PERCENTAGE", "%");
	define("PHP", "php");
	define("PHP_INPUT", "php://input");
	define("POINT", ".");	
	define("POST", "post");	
	define("PROJECT", "@_YOUR_PROJECT"); // Insert your project name here.
	define("PUT", "put");		
	define("SINGLE_QUOTATION_MARKS", "'");
	define("R", "r");		
	define("READ", "read");	
	define("REQUEST", "request");		
	define("REQUEST_METHOD", "REQUEST_METHOD");	
	define("RES", "res");
	define("RESOURCE", "resource");
	define("RESPONSE", "response");	
	define("RIGHT_PARENTHESES", ")");	
	define("SELECT", "SELECT");	
	define("SEMICOLON", ";");	
	define("SET", "SET");
	define("SIZE", "size");		
	define("SRC_CONTROLLER", "\src\controller\\");	
	define("STATE", "state");
	define("STATUS", "status");
	define("STRING_AND", "AND");
	define("STRING_AS", "AS");		
	define("STRING_BETWEEN", "between");	
	define("STRING_CLASS", "class");
	define("STRING_DATE_FORMAT", "0000-00-00");
	define("STRING_DATETIME_FORMAT", "0000-00-00 00:00:00");	
	define("STRING_EMPTY", "");		
	define("STRING_EQUALS", "equals");
	define("STRING_FALSE", "false");
	define("STRING_MORE_EQUALS", "more-equals");
	define("STRING_MORE_THAN", "more-than");		
	define("STRING_NOT_EQUALS", "not-equals");
	define("STRING_NOT_IN", "not-in");
	define("STRING_LESS_EQUALS", "less-equals");	
	define("STRING_LESS_THAN", "less-than");		
	define("STRING_TRUE", "true");	
	define("STRING_OR", "OR");
	define("SUCCESS", "Success!");
	define("THE_ATTRIBUTE", "The attribute ");
	define("UPDATE", "update");
	define("USER", "user");
	define("VALUE", "value");	
	define("VALUES", "VALUES");	
	define("WHERE", "WHERE");
	define("WHITE_SPACE", " ");	
	define("XML", "xml");
	define("YMD_HIS", "Y-m-d H:i:s");
	define("CORES", "cores");
	define("CORES_INPUT", "coresInput");
	define("COR", "cor");
	define("HEXADECIMAL", "hexadecimal");
	define("CADASTRADO", "cadastrado");
	define("MODIFICADO", "modificado");
	define("TIPO_COR", "tipo_cor");
	define("MENU_SUBMENUS", "menu_submenus");
	define("MENU_SUBMENUS_INPUT", "menu_submenusInput");
	define("MENU_SUBMENU", "menu_submenu");
	define("LINK", "link");
	define("ORDEM", "ordem");
	define("MENU", "menu");
	define("SITUACAO_REGISTRO", "situacao_registro");
	define("MENUS", "menus");
	define("MENUS_INPUT", "menusInput");
	define("TIPO_MENU", "tipo_menu");
	define("PERFIL_TELA", "perfil_tela");
	define("PERFIL_TELA_INPUT", "perfil_telaInput");
	define("PERFIL", "perfil");
	define("TIPO_PERMISSAO", "tipo_permissao");
	define("TELA", "tela");
	define("PERFIS", "perfis");
	define("PERFIS_INPUT", "perfisInput");
	define("SITUACOES_REGISTROS", "situacoes_registros");
	define("SITUACOES_REGISTROS_INPUT", "situacoes_registrosInput");
	define("TELAS", "telas");
	define("TELAS_INPUT", "telasInput");
	define("IDENTIFICADOR", "identificador");
	define("TIPOS_CORES", "tipos_cores");
	define("TIPOS_CORES_INPUT", "tipos_coresInput");
	define("TIPOS_MENUS", "tipos_menus");
	define("TIPOS_MENUS_INPUT", "tipos_menusInput");
	define("TIPOS_PERMISSOES", "tipos_permissoes");
	define("TIPOS_PERMISSOES_INPUT", "tipos_permissoesInput");
	define("USUARIOS", "usuarios");
	define("USUARIOS_INPUT", "usuariosInput");
	define("USUARIO", "usuario");
	define("CPF", "cpf");
	define("EMAIL", "email");
	define("SENHA", "senha");
	define("FOTO", "foto");
	define("ACCESS_TOKEN", "access_token");
	define("ACCESS_TOKEN_EXPIRATION", "access_token_expiration");
	define("PASSWORD_TOKEN", "password_token");
	define("PASSWORD_TOKEN_EXPIRATION", "password_token_expiration");
	define("ACTIVATION_TOKEN", "activation_token");
	define("ACTIVATION_TOKEN_EXPIRATION", "activation_token_expiration");
			
		?>