<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use lib\getz;		
	use src\model;

	class Alterar_a_minha_senhaInput extends getz\Inject {
		
		private $senha;
			
		private $error;	
			
		public function __construct($request) { 
			if (isset($request[ID])) {
				$this->id = $this->inject($request[ID]);	
			}

			if (isset($request[SENHA])) {
				$this->senha = $this->inject($request[SENHA]);	
			}
		}
					
		public function getSenha() {
			return $this->senha;
		}
		
		public function setSenha($senha) {
			$this->senha = $senha;
		}
					
		public function getError() {
			return $this->error;
		}
		
		private function setError($error) {
			$this->error = $error;
		}	

		public function isValid($method) {		
			if ($method == POST) {
				if ($this->senha == null || $this->senha == STRING_EMPTY) {
					$this->setError(THE_ATTRIBUTE . SENHA . IS_REQUIRED);
					return false;					
				} 
				return true;
			}
		}
	}
	
?>