<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 

	class Cores {
			
		private $id;
		private $cor;
		private $hexadecimal;
		private $cadastrado;
		private $modificado;
		private $tipos_cores;
			
		public function __construct() { }
			
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}		
					
		public function getCor() {
			return $this->cor;
		}
		
		public function setCor($cor) {
			$this->cor = $cor;
		}		
					
		public function getHexadecimal() {
			return $this->hexadecimal;
		}
		
		public function setHexadecimal($hexadecimal) {
			$this->hexadecimal = $hexadecimal;
		}		
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}		
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}		
					
		public function getTipos_cores() {
			return $this->tipos_cores;
		}
		
		public function setTipos_cores($tipos_cores) {
			$this->tipos_cores = $tipos_cores;
		}		
					
	}
	
?>