<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use lib\getz;
	use src\model;

	class CoresInput extends getz\Inject {
			
		private $id;
		private $cor;
		private $hexadecimal;
		private $cadastrado;
		private $modificado;
		private $tipos_coresInput;
			
		private $error;	
			
		public function __construct($request) { 
			if (isset($request[ID])) {
				$this->id = $this->inject($request[ID]);	
			}
			if (isset($request[COR])) {
				$this->cor = $this->inject($request[COR]);	
			}
			if (isset($request[HEXADECIMAL])) {
				$this->hexadecimal = $this->inject($request[HEXADECIMAL]);	
			}
			if (isset($request[CADASTRADO])) {
				$this->cadastrado = $this->inject($request[CADASTRADO]);	
			}
			if (isset($request[MODIFICADO])) {
				$this->modificado = $this->inject($request[MODIFICADO]);	
			}
			if (isset($request[TIPOS_CORES_INPUT]) && isset($request[TIPOS_CORES_INPUT][ID])) {
				$tipos_coresInput = new model\Tipos_coresInput($request[TIPOS_CORES_INPUT]);
				$this->tipos_coresInput = $tipos_coresInput;	
			}
		}
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getCor() {
			return $this->cor;
		}
		
		public function setCor($cor) {
			$this->cor = $cor;
		}
					
		public function getHexadecimal() {
			return $this->hexadecimal;
		}
		
		public function setHexadecimal($hexadecimal) {
			$this->hexadecimal = $hexadecimal;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getTipos_coresInput() {
			return $this->tipos_coresInput;
		}
		
		public function setTipos_coresInput($tipos_coresInput) {
			$this->tipos_coresInput = $tipos_coresInput;
		}	
			
		public function getError() {
			return $this->error;
		}
		
		private function setError($error) {
			$this->error = $error;
		}	

		public function isValid($method) {		
			if ($method == POST) {
				if (is_null($this->cor) || empty($this->cor)) {
					$this->setError(THE_ATTRIBUTE . COR . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->hexadecimal) || empty($this->hexadecimal)) {
					$this->setError(THE_ATTRIBUTE . HEXADECIMAL . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->tipos_coresInput) || is_null($this->tipos_coresInput->getId()) || empty($this->tipos_coresInput->getId())) {
					$this->setError(THE_ATTRIBUTE . TIPOS_CORES_INPUT . DOT . ID . IS_REQUIRED);
					return false;					
				} 
				return true;
			} else if ($method == PUT) {
				if (is_null($this->id) || empty($this->id)) {
					$this->setError(THE_ATTRIBUTE . ID . IS_REQUIRED);
					return false;					
				} else {
					return true;
				}
			}
		}
		
		public function getEntity() {
			$cores = new model\Cores();
			if (!is_null($this->id)) {
				$cores->setId($this->id);
			}
			if (!is_null($this->cor)) {
				$cores->setCor($this->cor);	
			}
			if (!is_null($this->hexadecimal)) {
				$cores->setHexadecimal($this->hexadecimal);	
			} 
			$cores->setCadastrado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			$cores->setModificado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			if (!is_null($this->tipos_coresInput)) {
				$tipos_cores = $this->tipos_coresInput->getEntity();
				$cores->setTipos_cores($tipos_cores);
			}
			return $cores;
		}		
		
	}
	
?>