<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use lib\getz;	
	use src\model;

	class Efetuar_o_loginInput extends getz\Inject {
			
		private $email;
		private $senha;
			
		private $error;	
			
		public function __construct($request) { 
			if (isset($request[EMAIL])) {
				$this->email = $this->inject($request[EMAIL]);	
			}
			if (isset($request[SENHA])) {
				$this->senha = $this->inject($request[SENHA]);	
			}
		}
					
		public function getEmail() {
			return $this->email;
		}
		
		public function setEmail($email) {
			$this->email = $email;
		}
					
		public function getSenha() {
			return $this->senha;
		}
		
		public function setSenha($senha) {
			$this->senha = $senha;
		}
					
		public function getError() {
			return $this->error;
		}
		
		private function setError($error) {
			$this->error = $error;
		}	

		public function isValid($method) {		
			if ($method == POST) {
				if ($this->email == null || $this->email == STRING_EMPTY) {
					$this->setError(THE_ATTRIBUTE . EMAIL . IS_REQUIRED);
					return false;					
				} 
				if ($this->senha == null || $this->senha == STRING_EMPTY) {
					$this->setError(THE_ATTRIBUTE . SENHA . IS_REQUIRED);
					return false;					
				} else {
					return true;
				}
			}
		}
	}
	
?>