<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 

	class Menu_submenus {
			
		private $id;
		private $menu_submenu;
		private $link;
		private $ordem;
		private $cadastrado;
		private $modificado;
		private $menus;
		private $situacoes_registros;
			
		public function __construct() { }
			
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}		
					
		public function getMenu_submenu() {
			return $this->menu_submenu;
		}
		
		public function setMenu_submenu($menu_submenu) {
			$this->menu_submenu = $menu_submenu;
		}		
					
		public function getLink() {
			return $this->link;
		}
		
		public function setLink($link) {
			$this->link = $link;
		}		
					
		public function getOrdem() {
			return $this->ordem;
		}
		
		public function setOrdem($ordem) {
			$this->ordem = $ordem;
		}		
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}		
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}		
					
		public function getMenus() {
			return $this->menus;
		}
		
		public function setMenus($menus) {
			$this->menus = $menus;
		}		
					
		public function getSituacoes_registros() {
			return $this->situacoes_registros;
		}
		
		public function setSituacoes_registros($situacoes_registros) {
			$this->situacoes_registros = $situacoes_registros;
		}		
					
	}
	
?>