<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class Menu_submenusOutput implements \JsonSerializable {
			
		private $id;
		private $menu_submenu;
		private $link;
		private $ordem;
		private $cadastrado;
		private $modificado;
		private $menusOutput;
		private $situacoes_registrosOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getMenu_submenu() {
			return $this->menu_submenu;
		}
		
		public function setMenu_submenu($menu_submenu) {
			$this->menu_submenu = $menu_submenu;
		}
					
		public function getLink() {
			return $this->link;
		}
		
		public function setLink($link) {
			$this->link = $link;
		}
					
		public function getOrdem() {
			return $this->ordem;
		}
		
		public function setOrdem($ordem) {
			$this->ordem = $ordem;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getMenusOutput() {
			return $this->menusOutput;
		}
		
		public function setMenusOutput($menusOutput) {
			$this->menusOutput = $menusOutput;
		}
					
		public function getSituacoes_registrosOutput() {
			return $this->situacoes_registrosOutput;
		}
		
		public function setSituacoes_registrosOutput($situacoes_registrosOutput) {
			$this->situacoes_registrosOutput = $situacoes_registrosOutput;
		}

		public function getOutput($menu_submenus) {
			if (!is_null($menu_submenus)) {
				$menu_submenusOutput = new model\Menu_submenusOutput();
				$menu_submenusOutput->setId($menu_submenus->getId());
				$menu_submenusOutput->setMenu_submenu($menu_submenus->getMenu_submenu());
				$menu_submenusOutput->setLink($menu_submenus->getLink());
				$menu_submenusOutput->setOrdem($menu_submenus->getOrdem());
				$menusOutput = new model\MenusOutput();
				$menu_submenusOutput->setMenusOutput($menusOutput->getOutput($menu_submenus->getMenus()));
				$situacoes_registrosOutput = new model\Situacoes_registrosOutput();
				$menu_submenusOutput->setSituacoes_registrosOutput($situacoes_registrosOutput->getOutput($menu_submenus->getSituacoes_registros()));
				return $menu_submenusOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($menu_submenusList) {
			$menu_submenusOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($menu_submenusList); $x++) {
				$menu_submenusOutputList[$count] = $this->getOutput($menu_submenusList[$x]);
				$count++;
			}
			return $menu_submenusOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>