<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class MenusOutput implements \JsonSerializable {
			
		private $id;
		private $menu;
		private $link;
		private $ordem;
		private $cadastrado;
		private $modificado;
		private $tipos_menusOutput;
		private $situacoes_registrosOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getMenu() {
			return $this->menu;
		}
		
		public function setMenu($menu) {
			$this->menu = $menu;
		}
					
		public function getLink() {
			return $this->link;
		}
		
		public function setLink($link) {
			$this->link = $link;
		}
					
		public function getOrdem() {
			return $this->ordem;
		}
		
		public function setOrdem($ordem) {
			$this->ordem = $ordem;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getTipos_menusOutput() {
			return $this->tipos_menusOutput;
		}
		
		public function setTipos_menusOutput($tipos_menusOutput) {
			$this->tipos_menusOutput = $tipos_menusOutput;
		}
					
		public function getSituacoes_registrosOutput() {
			return $this->situacoes_registrosOutput;
		}
		
		public function setSituacoes_registrosOutput($situacoes_registrosOutput) {
			$this->situacoes_registrosOutput = $situacoes_registrosOutput;
		}

		public function getOutput($menus) {
			if (!is_null($menus)) {
				$menusOutput = new model\MenusOutput();
				$menusOutput->setId($menus->getId());
				$menusOutput->setMenu($menus->getMenu());
				$menusOutput->setLink($menus->getLink());
				$menusOutput->setOrdem($menus->getOrdem());
				$tipos_menusOutput = new model\Tipos_menusOutput();
				$menusOutput->setTipos_menusOutput($tipos_menusOutput->getOutput($menus->getTipos_menus()));
				$situacoes_registrosOutput = new model\Situacoes_registrosOutput();
				$menusOutput->setSituacoes_registrosOutput($situacoes_registrosOutput->getOutput($menus->getSituacoes_registros()));
				return $menusOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($menusList) {
			$menusOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($menusList); $x++) {
				$menusOutputList[$count] = $this->getOutput($menusList[$x]);
				$count++;
			}
			return $menusOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>