<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use lib\getz;
	use src\model;

	class Menu_submenusInput extends getz\Inject {
			
		private $id;
		private $menu_submenu;
		private $link;
		private $ordem;
		private $cadastrado;
		private $modificado;
		private $menusInput;
		private $situacoes_registrosInput;
			
		private $error;	
			
		public function __construct($request) { 
			if (isset($request[ID])) {
				$this->id = $this->inject($request[ID]);	
			}
			if (isset($request[MENU_SUBMENU])) {
				$this->menu_submenu = $this->inject($request[MENU_SUBMENU]);	
			}
			if (isset($request[LINK])) {
				$this->link = $this->inject($request[LINK]);	
			}
			if (isset($request[ORDEM])) {
				$this->ordem = $this->inject($request[ORDEM]);	
			}
			if (isset($request[CADASTRADO])) {
				$this->cadastrado = $this->inject($request[CADASTRADO]);	
			}
			if (isset($request[MODIFICADO])) {
				$this->modificado = $this->inject($request[MODIFICADO]);	
			}
			if (isset($request[MENUS_INPUT]) && isset($request[MENUS_INPUT][ID])) {
				$menusInput = new model\MenusInput($request[MENUS_INPUT]);
				$this->menusInput = $menusInput;	
			}
			if (isset($request[SITUACOES_REGISTROS_INPUT]) && isset($request[SITUACOES_REGISTROS_INPUT][ID])) {
				$situacoes_registrosInput = new model\Situacoes_registrosInput($request[SITUACOES_REGISTROS_INPUT]);
				$this->situacoes_registrosInput = $situacoes_registrosInput;	
			}
		}
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getMenu_submenu() {
			return $this->menu_submenu;
		}
		
		public function setMenu_submenu($menu_submenu) {
			$this->menu_submenu = $menu_submenu;
		}
					
		public function getLink() {
			return $this->link;
		}
		
		public function setLink($link) {
			$this->link = $link;
		}
					
		public function getOrdem() {
			return $this->ordem;
		}
		
		public function setOrdem($ordem) {
			$this->ordem = $ordem;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getMenusInput() {
			return $this->menusInput;
		}
		
		public function setMenusInput($menusInput) {
			$this->menusInput = $menusInput;
		}
					
		public function getSituacoes_registrosInput() {
			return $this->situacoes_registrosInput;
		}
		
		public function setSituacoes_registrosInput($situacoes_registrosInput) {
			$this->situacoes_registrosInput = $situacoes_registrosInput;
		}	
			
		public function getError() {
			return $this->error;
		}
		
		private function setError($error) {
			$this->error = $error;
		}	

		public function isValid($method) {		
			if ($method == POST) {
				if (is_null($this->menu_submenu) || empty($this->menu_submenu)) {
					$this->setError(THE_ATTRIBUTE . MENU_SUBMENU . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->link) || empty($this->link)) {
					$this->setError(THE_ATTRIBUTE . LINK . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->ordem) || empty($this->ordem)) {
					$this->setError(THE_ATTRIBUTE . ORDEM . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->menusInput) || is_null($this->menusInput->getId()) || empty($this->menusInput->getId())) {
					$this->setError(THE_ATTRIBUTE . MENUS_INPUT . DOT . ID . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->situacoes_registrosInput) || is_null($this->situacoes_registrosInput->getId()) || empty($this->situacoes_registrosInput->getId())) {
					$this->setError(THE_ATTRIBUTE . SITUACOES_REGISTROS_INPUT . DOT . ID . IS_REQUIRED);
					return false;					
				} 
				return true;
			} else if ($method == PUT) {
				if (is_null($this->id) || empty($this->id)) {
					$this->setError(THE_ATTRIBUTE . ID . IS_REQUIRED);
					return false;					
				} else {
					return true;
				}
			}
		}
		
		public function getEntity() {
			$menu_submenus = new model\Menu_submenus();
			if (!is_null($this->id)) {
				$menu_submenus->setId($this->id);
			}
			if (!is_null($this->menu_submenu)) {
				$menu_submenus->setMenu_submenu($this->menu_submenu);	
			}
			if (!is_null($this->link)) {
				$menu_submenus->setLink($this->link);	
			}
			if (!is_null($this->ordem)) {
				$menu_submenus->setOrdem($this->ordem);	
			} 
			$menu_submenus->setCadastrado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			$menu_submenus->setModificado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			if (!is_null($this->menusInput)) {
				$menus = $this->menusInput->getEntity();
				$menu_submenus->setMenus($menus);
			}
			if (!is_null($this->situacoes_registrosInput)) {
				$situacoes_registros = $this->situacoes_registrosInput->getEntity();
				$menu_submenus->setSituacoes_registros($situacoes_registros);
			}
			return $menu_submenus;
		}		
		
	}
	
?>