<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class PerfisOutput implements \JsonSerializable {
			
		private $id;
		private $perfil;
		private $cadastrado;
		private $modificado;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getPerfil() {
			return $this->perfil;
		}
		
		public function setPerfil($perfil) {
			$this->perfil = $perfil;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}

		public function getOutput($perfis) {
			if (!is_null($perfis)) {
				$perfisOutput = new model\PerfisOutput();
				$perfisOutput->setId($perfis->getId());
				$perfisOutput->setPerfil($perfis->getPerfil());
				return $perfisOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($perfisList) {
			$perfisOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($perfisList); $x++) {
				$perfisOutputList[$count] = $this->getOutput($perfisList[$x]);
				$count++;
			}
			return $perfisOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>