<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use lib\getz;
	use src\model;

	class Perfil_telaInput extends getz\Inject {
			
		private $id;
		private $cadastrado;
		private $modificado;
		private $perfisInput;
		private $tipos_permissoesInput;
		private $telasInput;
			
		private $error;	
			
		public function __construct($request) { 
			if (isset($request[ID])) {
				$this->id = $this->inject($request[ID]);	
			}
			if (isset($request[CADASTRADO])) {
				$this->cadastrado = $this->inject($request[CADASTRADO]);	
			}
			if (isset($request[MODIFICADO])) {
				$this->modificado = $this->inject($request[MODIFICADO]);	
			}
			if (isset($request[PERFIS_INPUT]) && isset($request[PERFIS_INPUT][ID])) {
				$perfisInput = new model\PerfisInput($request[PERFIS_INPUT]);
				$this->perfisInput = $perfisInput;	
			}
			if (isset($request[TIPOS_PERMISSOES_INPUT]) && isset($request[TIPOS_PERMISSOES_INPUT][ID])) {
				$tipos_permissoesInput = new model\Tipos_permissoesInput($request[TIPOS_PERMISSOES_INPUT]);
				$this->tipos_permissoesInput = $tipos_permissoesInput;	
			}
			if (isset($request[TELAS_INPUT]) && isset($request[TELAS_INPUT][ID])) {
				$telasInput = new model\TelasInput($request[TELAS_INPUT]);
				$this->telasInput = $telasInput;	
			}
		}
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getPerfisInput() {
			return $this->perfisInput;
		}
		
		public function setPerfisInput($perfisInput) {
			$this->perfisInput = $perfisInput;
		}
					
		public function getTipos_permissoesInput() {
			return $this->tipos_permissoesInput;
		}
		
		public function setTipos_permissoesInput($tipos_permissoesInput) {
			$this->tipos_permissoesInput = $tipos_permissoesInput;
		}
					
		public function getTelasInput() {
			return $this->telasInput;
		}
		
		public function setTelasInput($telasInput) {
			$this->telasInput = $telasInput;
		}	
			
		public function getError() {
			return $this->error;
		}
		
		private function setError($error) {
			$this->error = $error;
		}	

		public function isValid($method) {		
			if ($method == POST) {
				if (is_null($this->perfisInput) || is_null($this->perfisInput->getId()) || empty($this->perfisInput->getId())) {
					$this->setError(THE_ATTRIBUTE . PERFIS_INPUT . DOT . ID . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->tipos_permissoesInput) || is_null($this->tipos_permissoesInput->getId()) || empty($this->tipos_permissoesInput->getId())) {
					$this->setError(THE_ATTRIBUTE . TIPOS_PERMISSOES_INPUT . DOT . ID . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->telasInput) || is_null($this->telasInput->getId()) || empty($this->telasInput->getId())) {
					$this->setError(THE_ATTRIBUTE . TELAS_INPUT . DOT . ID . IS_REQUIRED);
					return false;					
				} 
				return true;
			} else if ($method == PUT) {
				if (is_null($this->id) || empty($this->id)) {
					$this->setError(THE_ATTRIBUTE . ID . IS_REQUIRED);
					return false;					
				} else {
					return true;
				}
			}
		}
		
		public function getEntity() {
			$perfil_tela = new model\Perfil_tela();
			if (!is_null($this->id)) {
				$perfil_tela->setId($this->id);
			} 
			$perfil_tela->setCadastrado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			$perfil_tela->setModificado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			if (!is_null($this->perfisInput)) {
				$perfis = $this->perfisInput->getEntity();
				$perfil_tela->setPerfis($perfis);
			}
			if (!is_null($this->tipos_permissoesInput)) {
				$tipos_permissoes = $this->tipos_permissoesInput->getEntity();
				$perfil_tela->setTipos_permissoes($tipos_permissoes);
			}
			if (!is_null($this->telasInput)) {
				$telas = $this->telasInput->getEntity();
				$perfil_tela->setTelas($telas);
			}
			return $perfil_tela;
		}		
		
	}
	
?>