<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class Perfil_telaOutput implements \JsonSerializable {
			
		private $id;
		private $cadastrado;
		private $modificado;
		private $perfisOutput;
		private $tipos_permissoesOutput;
		private $telasOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getPerfisOutput() {
			return $this->perfisOutput;
		}
		
		public function setPerfisOutput($perfisOutput) {
			$this->perfisOutput = $perfisOutput;
		}
					
		public function getTipos_permissoesOutput() {
			return $this->tipos_permissoesOutput;
		}
		
		public function setTipos_permissoesOutput($tipos_permissoesOutput) {
			$this->tipos_permissoesOutput = $tipos_permissoesOutput;
		}
					
		public function getTelasOutput() {
			return $this->telasOutput;
		}
		
		public function setTelasOutput($telasOutput) {
			$this->telasOutput = $telasOutput;
		}

		public function getOutput($perfil_tela) {
			if (!is_null($perfil_tela)) {
				$perfil_telaOutput = new model\Perfil_telaOutput();
				$perfil_telaOutput->setId($perfil_tela->getId());
				$perfisOutput = new model\PerfisOutput();
				$perfil_telaOutput->setPerfisOutput($perfisOutput->getOutput($perfil_tela->getPerfis()));
				$tipos_permissoesOutput = new model\Tipos_permissoesOutput();
				$perfil_telaOutput->setTipos_permissoesOutput($tipos_permissoesOutput->getOutput($perfil_tela->getTipos_permissoes()));
				$telasOutput = new model\TelasOutput();
				$perfil_telaOutput->setTelasOutput($telasOutput->getOutput($perfil_tela->getTelas()));
				return $perfil_telaOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($perfil_telaList) {
			$perfil_telaOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($perfil_telaList); $x++) {
				$perfil_telaOutputList[$count] = $this->getOutput($perfil_telaList[$x]);
				$count++;
			}
			return $perfil_telaOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>