<?php
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz 
	 * @since   1.0.0
	 * @version 1.0.0	 
	 */
	 
	namespace src\model; 
	use src\model;
	
	class PerfisDao {
		
		private $connection;
		private $size;
		private $log;
		private $columns = PERFIS . DOT. ID . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . PERFIS . DOT . ID . DOUBLE_QUOTES . COMMA . WHITE_SPACE . PERFIS . DOT. PERFIL . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . PERFIS . DOT . PERFIL . DOUBLE_QUOTES . COMMA . WHITE_SPACE . PERFIS . DOT. CADASTRADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . PERFIS . DOT . CADASTRADO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . PERFIS . DOT. MODIFICADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . PERFIS . DOT . MODIFICADO . DOUBLE_QUOTES;
		
		public function __construct($connection) {
			$this->connection = $connection;
		}
		
		public function getInsertId() {
			return $this->connection->getInsertId();
		}

		public function getSize() {
			return $this->size;
		}

		private function setLog($log) {
			$this->log = $log;
		}
		
		public function getLog() {
			return $this->log;
		}
		
		public function getColumns() {
			return $this->columns;
		}
		
		public function create($perfis) {
			$query = INSERT . WHITE_SPACE . INTO . WHITE_SPACE . PERFIS . WHITE_SPACE . LEFT_PARENTHESES . PERFIL . COMMA . WHITE_SPACE . CADASTRADO . COMMA . WHITE_SPACE . MODIFICADO . RIGHT_PARENTHESES . WHITE_SPACE . VALUES . WHITE_SPACE . LEFT_PARENTHESES . DOUBLE_QUOTES . $perfis->getPerfil() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $perfis->getCadastrado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $perfis->getModificado() . DOUBLE_QUOTES . RIGHT_PARENTHESES;
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function read($where, $order, $hasPagination) {
			$count = NUMBER_ZERO;
			if ($where != STRING_EMPTY) {
				$where = WHERE . WHITE_SPACE . $where;
			}
			if ($order != STRING_EMPTY) {
				$order = ORDER_BY . WHITE_SPACE . $order;
			}
			$query = SELECT . WHITE_SPACE . $this->columns . WHITE_SPACE . FROM . WHITE_SPACE . PERFIS . WHITE_SPACE . PERFIS . WHITE_SPACE . $where;
			$this->setLog($query . WHITE_SPACE . $order);
			$result = $this->connection->execute($query . WHITE_SPACE . $order);
			$perfisList = array();
			while ($row = $result->fetch_assoc()) {
				$perfis = new model\Perfis();
				$perfis->setId($row[PERFIS . POINT . ID]);
				$perfis->setPerfil($row[PERFIS . POINT . PERFIL]);
				$perfis->setCadastrado($row[PERFIS . POINT . CADASTRADO]);
				$perfis->setModificado($row[PERFIS . POINT . MODIFICADO]);
				$perfisList[$count] = $perfis;
				$count++;
			}
			$this->connection->free($result);
			if ($hasPagination && $count > NUMBER_ZERO) {
				$result = $this->connection->execute($query);
				$size = NUMBER_ZERO;
				while ($row = $result->fetch_assoc()) {
					$size++;
				}
				$this->connection->free($result);				
				$this->size = $size;
			}
			return $perfisList;
		}

		public function update($perfis) {
			$query = UPDATE . WHITE_SPACE . PERFIS . WHITE_SPACE . SET . WHITE_SPACE . ID . WHITE_SPACE . EQUALS . 
					WHITE_SPACE . DOUBLE_QUOTES . $perfis->getId() . DOUBLE_QUOTES;
			if (!is_null($perfis->getPerfil()) && !empty($perfis->getPerfil())) {
				$query .= COMMA . WHITE_SPACE . PERFIL . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$perfis->getPerfil() . DOUBLE_QUOTES;
			}
			$query .= COMMA . WHITE_SPACE . MODIFICADO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
					$perfis->getModificado() . DOUBLE_QUOTES . WHITE_SPACE . WHERE . WHITE_SPACE . ID . EQUALS . 
					$perfis->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function delete($perfis) {
			$query = DELETE . WHITE_SPACE . FROM . WHITE_SPACE . PERFIS . WHITE_SPACE . WHERE . WHITE_SPACE . ID . 
					WHITE_SPACE . EQUALS . WHITE_SPACE . $perfis->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

	}

?>