<?php
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz 
	 * @since   1.0.0
	 * @version 1.0.0	 
	 */
	 
	namespace src\model; 
	use src\model;
	
	class Situacoes_registrosDao {
		
		private $connection;
		private $size;
		private $log;
		private $columns = SITUACOES_REGISTROS . DOT. ID . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . SITUACOES_REGISTROS . DOT . ID . DOUBLE_QUOTES . COMMA . WHITE_SPACE . SITUACOES_REGISTROS . DOT. SITUACAO_REGISTRO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . SITUACOES_REGISTROS . DOT . SITUACAO_REGISTRO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . SITUACOES_REGISTROS . DOT. CADASTRADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . SITUACOES_REGISTROS . DOT . CADASTRADO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . SITUACOES_REGISTROS . DOT. MODIFICADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . SITUACOES_REGISTROS . DOT . MODIFICADO . DOUBLE_QUOTES;
		
		public function __construct($connection) {
			$this->connection = $connection;
		}
		
		public function getInsertId() {
			return $this->connection->getInsertId();
		}

		public function getSize() {
			return $this->size;
		}

		private function setLog($log) {
			$this->log = $log;
		}
		
		public function getLog() {
			return $this->log;
		}
		
		public function getColumns() {
			return $this->columns;
		}
		
		public function create($situacoes_registros) {
			$query = INSERT . WHITE_SPACE . INTO . WHITE_SPACE . SITUACOES_REGISTROS . WHITE_SPACE . LEFT_PARENTHESES . SITUACAO_REGISTRO . COMMA . WHITE_SPACE . CADASTRADO . COMMA . WHITE_SPACE . MODIFICADO . COMMA . WHITE_SPACE . COR . RIGHT_PARENTHESES . WHITE_SPACE . VALUES . WHITE_SPACE . LEFT_PARENTHESES . DOUBLE_QUOTES . $situacoes_registros->getSituacao_registro() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $situacoes_registros->getCadastrado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $situacoes_registros->getModificado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $situacoes_registros->getCores()->getId() . DOUBLE_QUOTES . RIGHT_PARENTHESES;
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function read($where, $order, $hasPagination) {
			$count = NUMBER_ZERO;
			if ($where != STRING_EMPTY) {
				$where = WHERE . WHITE_SPACE . $where . WHITE_SPACE . STRING_AND . WHITE_SPACE . SITUACOES_REGISTROS . DOT . COR . WHITE_SPACE . EQUALS . WHITE_SPACE. CORES . DOT . ID;
			} else {
				$where = WHERE . WHITE_SPACE . SITUACOES_REGISTROS . DOT . COR . WHITE_SPACE . EQUALS . WHITE_SPACE. CORES . DOT . ID;
			}
			if ($order != STRING_EMPTY) {
				$order = ORDER_BY . WHITE_SPACE . $order;
			}
			$coresDao = new model\CoresDao($this->connection);
			$query = SELECT . WHITE_SPACE . $this->columns . COMMA . WHITE_SPACE . $coresDao->getColumns() . WHITE_SPACE . FROM . WHITE_SPACE . SITUACOES_REGISTROS . WHITE_SPACE . SITUACOES_REGISTROS . COMMA . WHITE_SPACE . CORES . WHITE_SPACE . CORES . WHITE_SPACE . $where;
			$this->setLog($query . WHITE_SPACE . $order);
			$result = $this->connection->execute($query . WHITE_SPACE . $order);
			$situacoes_registrosList = array();
			while ($row = $result->fetch_assoc()) {
				$situacoes_registros = new model\Situacoes_registros();
				$situacoes_registros->setId($row[SITUACOES_REGISTROS . POINT . ID]);
				$situacoes_registros->setSituacao_registro($row[SITUACOES_REGISTROS . POINT . SITUACAO_REGISTRO]);
				$situacoes_registros->setCadastrado($row[SITUACOES_REGISTROS . POINT . CADASTRADO]);
				$situacoes_registros->setModificado($row[SITUACOES_REGISTROS . POINT . MODIFICADO]);
				$cores = new model\Cores();
				$cores->setId($row[CORES . DOT . ID]);
				$cores->setCor($row[CORES . DOT . COR]);
				$situacoes_registros->setCores($cores);
				$situacoes_registrosList[$count] = $situacoes_registros;
				$count++;
			}
			$this->connection->free($result);
			if ($hasPagination && $count > NUMBER_ZERO) {
				$result = $this->connection->execute($query);
				$size = NUMBER_ZERO;
				while ($row = $result->fetch_assoc()) {
					$size++;
				}
				$this->connection->free($result);				
				$this->size = $size;
			}
			return $situacoes_registrosList;
		}

		public function update($situacoes_registros) {
			$query = UPDATE . WHITE_SPACE . SITUACOES_REGISTROS . WHITE_SPACE . SET . WHITE_SPACE . ID . WHITE_SPACE . EQUALS . 
					WHITE_SPACE . DOUBLE_QUOTES . $situacoes_registros->getId() . DOUBLE_QUOTES;
			if (!is_null($situacoes_registros->getSituacao_registro()) && !empty($situacoes_registros->getSituacao_registro())) {
				$query .= COMMA . WHITE_SPACE . SITUACAO_REGISTRO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$situacoes_registros->getSituacao_registro() . DOUBLE_QUOTES;
			}
			if (!is_null($situacoes_registros->getCores()) && !empty($situacoes_registros->getCores()->getId()) &&  
					!empty($situacoes_registros->getCores()->getId())) {
				$query .= COMMA . WHITE_SPACE . COR . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$situacoes_registros->getCores()->getId() . DOUBLE_QUOTES;
			}
			$query .= COMMA . WHITE_SPACE . MODIFICADO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
					$situacoes_registros->getModificado() . DOUBLE_QUOTES . WHITE_SPACE . WHERE . WHITE_SPACE . ID . EQUALS . 
					$situacoes_registros->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function delete($situacoes_registros) {
			$query = DELETE . WHITE_SPACE . FROM . WHITE_SPACE . SITUACOES_REGISTROS . WHITE_SPACE . WHERE . WHITE_SPACE . ID . 
					WHITE_SPACE . EQUALS . WHITE_SPACE . $situacoes_registros->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

	}

?>