<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class Situacoes_registrosOutput implements \JsonSerializable {
			
		private $id;
		private $situacao_registro;
		private $cadastrado;
		private $modificado;
		private $coresOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getSituacao_registro() {
			return $this->situacao_registro;
		}
		
		public function setSituacao_registro($situacao_registro) {
			$this->situacao_registro = $situacao_registro;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getCoresOutput() {
			return $this->coresOutput;
		}
		
		public function setCoresOutput($coresOutput) {
			$this->coresOutput = $coresOutput;
		}

		public function getOutput($situacoes_registros) {
			if (!is_null($situacoes_registros)) {
				$situacoes_registrosOutput = new model\Situacoes_registrosOutput();
				$situacoes_registrosOutput->setId($situacoes_registros->getId());
				$situacoes_registrosOutput->setSituacao_registro($situacoes_registros->getSituacao_registro());
				$coresOutput = new model\CoresOutput();
				$situacoes_registrosOutput->setCoresOutput($coresOutput->getOutput($situacoes_registros->getCores()));
				return $situacoes_registrosOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($situacoes_registrosList) {
			$situacoes_registrosOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($situacoes_registrosList); $x++) {
				$situacoes_registrosOutputList[$count] = $this->getOutput($situacoes_registrosList[$x]);
				$count++;
			}
			return $situacoes_registrosOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>