<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class TelasOutput implements \JsonSerializable {
			
		private $id;
		private $tela;
		private $identificador;
		private $cadastrado;
		private $modificado;
		private $menusOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getTela() {
			return $this->tela;
		}
		
		public function setTela($tela) {
			$this->tela = $tela;
		}
					
		public function getIdentificador() {
			return $this->identificador;
		}
		
		public function setIdentificador($identificador) {
			$this->identificador = $identificador;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getMenusOutput() {
			return $this->menusOutput;
		}
		
		public function setMenusOutput($menusOutput) {
			$this->menusOutput = $menusOutput;
		}

		public function getOutput($telas) {
			if (!is_null($telas)) {
				$telasOutput = new model\TelasOutput();
				$telasOutput->setId($telas->getId());
				$telasOutput->setTela($telas->getTela());
				$telasOutput->setIdentificador($telas->getIdentificador());
				$menusOutput = new model\MenusOutput();
				$telasOutput->setMenusOutput($menusOutput->getOutput($telas->getMenus()));
				return $telasOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($telasList) {
			$telasOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($telasList); $x++) {
				$telasOutputList[$count] = $this->getOutput($telasList[$x]);
				$count++;
			}
			return $telasOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>