<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use lib\getz;
	use src\model;

	class TelasInput extends getz\Inject {
			
		private $id;
		private $tela;
		private $identificador;
		private $cadastrado;
		private $modificado;
		private $menusInput;
			
		private $error;	
			
		public function __construct($request) { 
			if (isset($request[ID])) {
				$this->id = $this->inject($request[ID]);	
			}
			if (isset($request[TELA])) {
				$this->tela = $this->inject($request[TELA]);	
			}
			if (isset($request[IDENTIFICADOR])) {
				$this->identificador = $this->inject($request[IDENTIFICADOR]);	
			}
			if (isset($request[CADASTRADO])) {
				$this->cadastrado = $this->inject($request[CADASTRADO]);	
			}
			if (isset($request[MODIFICADO])) {
				$this->modificado = $this->inject($request[MODIFICADO]);	
			}
			if (isset($request[MENUS_INPUT]) && isset($request[MENUS_INPUT][ID])) {
				$menusInput = new model\MenusInput($request[MENUS_INPUT]);
				$this->menusInput = $menusInput;	
			}
		}
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getTela() {
			return $this->tela;
		}
		
		public function setTela($tela) {
			$this->tela = $tela;
		}
					
		public function getIdentificador() {
			return $this->identificador;
		}
		
		public function setIdentificador($identificador) {
			$this->identificador = $identificador;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getMenusInput() {
			return $this->menusInput;
		}
		
		public function setMenusInput($menusInput) {
			$this->menusInput = $menusInput;
		}	
			
		public function getError() {
			return $this->error;
		}
		
		private function setError($error) {
			$this->error = $error;
		}	

		public function isValid($method) {		
			if ($method == POST) {
				if (is_null($this->tela) || empty($this->tela)) {
					$this->setError(THE_ATTRIBUTE . TELA . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->identificador) || empty($this->identificador)) {
					$this->setError(THE_ATTRIBUTE . IDENTIFICADOR . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->menusInput) || is_null($this->menusInput->getId()) || empty($this->menusInput->getId())) {
					$this->setError(THE_ATTRIBUTE . MENUS_INPUT . DOT . ID . IS_REQUIRED);
					return false;					
				} 
				return true;
			} else if ($method == PUT) {
				if (is_null($this->id) || empty($this->id)) {
					$this->setError(THE_ATTRIBUTE . ID . IS_REQUIRED);
					return false;					
				} else {
					return true;
				}
			}
		}
		
		public function getEntity() {
			$telas = new model\Telas();
			if (!is_null($this->id)) {
				$telas->setId($this->id);
			}
			if (!is_null($this->tela)) {
				$telas->setTela($this->tela);	
			}
			if (!is_null($this->identificador)) {
				$telas->setIdentificador($this->identificador);	
			} 
			$telas->setCadastrado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			$telas->setModificado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			if (!is_null($this->menusInput)) {
				$menus = $this->menusInput->getEntity();
				$telas->setMenus($menus);
			}
			return $telas;
		}		
		
	}
	
?>