<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use lib\getz;
	use src\model;

	class Tipos_permissoesInput extends getz\Inject {
			
		private $id;
		private $tipo_permissao;
		private $cadastrado;
		private $modificado;
		private $coresInput;
			
		private $error;	
			
		public function __construct($request) { 
			if (isset($request[ID])) {
				$this->id = $this->inject($request[ID]);	
			}
			if (isset($request[TIPO_PERMISSAO])) {
				$this->tipo_permissao = $this->inject($request[TIPO_PERMISSAO]);	
			}
			if (isset($request[CADASTRADO])) {
				$this->cadastrado = $this->inject($request[CADASTRADO]);	
			}
			if (isset($request[MODIFICADO])) {
				$this->modificado = $this->inject($request[MODIFICADO]);	
			}
			if (isset($request[CORES_INPUT]) && isset($request[CORES_INPUT][ID])) {
				$coresInput = new model\CoresInput($request[CORES_INPUT]);
				$this->coresInput = $coresInput;	
			}
		}
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getTipo_permissao() {
			return $this->tipo_permissao;
		}
		
		public function setTipo_permissao($tipo_permissao) {
			$this->tipo_permissao = $tipo_permissao;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getCoresInput() {
			return $this->coresInput;
		}
		
		public function setCoresInput($coresInput) {
			$this->coresInput = $coresInput;
		}	
			
		public function getError() {
			return $this->error;
		}
		
		private function setError($error) {
			$this->error = $error;
		}	

		public function isValid($method) {		
			if ($method == POST) {
				if (is_null($this->tipo_permissao) || empty($this->tipo_permissao)) {
					$this->setError(THE_ATTRIBUTE . TIPO_PERMISSAO . IS_REQUIRED);
					return false;					
				} 
				if (is_null($this->coresInput) || is_null($this->coresInput->getId()) || empty($this->coresInput->getId())) {
					$this->setError(THE_ATTRIBUTE . CORES_INPUT . DOT . ID . IS_REQUIRED);
					return false;					
				} 
				return true;
			} else if ($method == PUT) {
				if (is_null($this->id) || empty($this->id)) {
					$this->setError(THE_ATTRIBUTE . ID . IS_REQUIRED);
					return false;					
				} else {
					return true;
				}
			}
		}
		
		public function getEntity() {
			$tipos_permissoes = new model\Tipos_permissoes();
			if (!is_null($this->id)) {
				$tipos_permissoes->setId($this->id);
			}
			if (!is_null($this->tipo_permissao)) {
				$tipos_permissoes->setTipo_permissao($this->tipo_permissao);	
			} 
			$tipos_permissoes->setCadastrado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			$tipos_permissoes->setModificado(date(YMD_HIS, (time() - ONE_HOUR_IN_SECONDS * BRAZILIAN_TIME_ZONE)));
			if (!is_null($this->coresInput)) {
				$cores = $this->coresInput->getEntity();
				$tipos_permissoes->setCores($cores);
			}
			return $tipos_permissoes;
		}		
		
	}
	
?>