<?php
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz 
	 * @since   1.0.0
	 * @version 1.0.0	 
	 */
	 
	namespace src\model; 
	use src\model;
	
	class Tipos_coresDao {
		
		private $connection;
		private $size;
		private $log;
		private $columns = TIPOS_CORES . DOT. ID . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_CORES . DOT . ID . DOUBLE_QUOTES . COMMA . WHITE_SPACE . TIPOS_CORES . DOT. TIPO_COR . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_CORES . DOT . TIPO_COR . DOUBLE_QUOTES . COMMA . WHITE_SPACE . TIPOS_CORES . DOT. CADASTRADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_CORES . DOT . CADASTRADO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . TIPOS_CORES . DOT. MODIFICADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_CORES . DOT . MODIFICADO . DOUBLE_QUOTES;
		
		public function __construct($connection) {
			$this->connection = $connection;
		}
		
		public function getInsertId() {
			return $this->connection->getInsertId();
		}

		public function getSize() {
			return $this->size;
		}

		private function setLog($log) {
			$this->log = $log;
		}
		
		public function getLog() {
			return $this->log;
		}
		
		public function getColumns() {
			return $this->columns;
		}
		
		public function create($tipos_cores) {
			$query = INSERT . WHITE_SPACE . INTO . WHITE_SPACE . TIPOS_CORES . WHITE_SPACE . LEFT_PARENTHESES . TIPO_COR . COMMA . WHITE_SPACE . CADASTRADO . COMMA . WHITE_SPACE . MODIFICADO . RIGHT_PARENTHESES . WHITE_SPACE . VALUES . WHITE_SPACE . LEFT_PARENTHESES . DOUBLE_QUOTES . $tipos_cores->getTipo_cor() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $tipos_cores->getCadastrado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $tipos_cores->getModificado() . DOUBLE_QUOTES . RIGHT_PARENTHESES;
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function read($where, $order, $hasPagination) {
			$count = NUMBER_ZERO;
			if ($where != STRING_EMPTY) {
				$where = WHERE . WHITE_SPACE . $where;
			}
			if ($order != STRING_EMPTY) {
				$order = ORDER_BY . WHITE_SPACE . $order;
			}
			$query = SELECT . WHITE_SPACE . $this->columns . WHITE_SPACE . FROM . WHITE_SPACE . TIPOS_CORES . WHITE_SPACE . TIPOS_CORES . WHITE_SPACE . $where;
			$this->setLog($query . WHITE_SPACE . $order);
			$result = $this->connection->execute($query . WHITE_SPACE . $order);
			$tipos_coresList = array();
			while ($row = $result->fetch_assoc()) {
				$tipos_cores = new model\Tipos_cores();
				$tipos_cores->setId($row[TIPOS_CORES . POINT . ID]);
				$tipos_cores->setTipo_cor($row[TIPOS_CORES . POINT . TIPO_COR]);
				$tipos_cores->setCadastrado($row[TIPOS_CORES . POINT . CADASTRADO]);
				$tipos_cores->setModificado($row[TIPOS_CORES . POINT . MODIFICADO]);
				$tipos_coresList[$count] = $tipos_cores;
				$count++;
			}
			$this->connection->free($result);
			if ($hasPagination && $count > NUMBER_ZERO) {
				$result = $this->connection->execute($query);
				$size = NUMBER_ZERO;
				while ($row = $result->fetch_assoc()) {
					$size++;
				}
				$this->connection->free($result);				
				$this->size = $size;
			}
			return $tipos_coresList;
		}

		public function update($tipos_cores) {
			$query = UPDATE . WHITE_SPACE . TIPOS_CORES . WHITE_SPACE . SET . WHITE_SPACE . ID . WHITE_SPACE . EQUALS . 
					WHITE_SPACE . DOUBLE_QUOTES . $tipos_cores->getId() . DOUBLE_QUOTES;
			if (!is_null($tipos_cores->getTipo_cor()) && !empty($tipos_cores->getTipo_cor())) {
				$query .= COMMA . WHITE_SPACE . TIPO_COR . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$tipos_cores->getTipo_cor() . DOUBLE_QUOTES;
			}
			$query .= COMMA . WHITE_SPACE . MODIFICADO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
					$tipos_cores->getModificado() . DOUBLE_QUOTES . WHITE_SPACE . WHERE . WHITE_SPACE . ID . EQUALS . 
					$tipos_cores->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function delete($tipos_cores) {
			$query = DELETE . WHITE_SPACE . FROM . WHITE_SPACE . TIPOS_CORES . WHITE_SPACE . WHERE . WHITE_SPACE . ID . 
					WHITE_SPACE . EQUALS . WHITE_SPACE . $tipos_cores->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

	}

?>