<?php
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz 
	 * @since   1.0.0
	 * @version 1.0.0	 
	 */
	 
	namespace src\model; 
	use src\model;
	
	class Tipos_menusDao {
		
		private $connection;
		private $size;
		private $log;
		private $columns = TIPOS_MENUS . DOT. ID . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_MENUS . DOT . ID . DOUBLE_QUOTES . COMMA . WHITE_SPACE . TIPOS_MENUS . DOT. TIPO_MENU . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_MENUS . DOT . TIPO_MENU . DOUBLE_QUOTES . COMMA . WHITE_SPACE . TIPOS_MENUS . DOT. CADASTRADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_MENUS . DOT . CADASTRADO . DOUBLE_QUOTES . COMMA . WHITE_SPACE . TIPOS_MENUS . DOT. MODIFICADO . WHITE_SPACE . STRING_AS . WHITE_SPACE . DOUBLE_QUOTES . TIPOS_MENUS . DOT . MODIFICADO . DOUBLE_QUOTES;
		
		public function __construct($connection) {
			$this->connection = $connection;
		}
		
		public function getInsertId() {
			return $this->connection->getInsertId();
		}

		public function getSize() {
			return $this->size;
		}

		private function setLog($log) {
			$this->log = $log;
		}
		
		public function getLog() {
			return $this->log;
		}
		
		public function getColumns() {
			return $this->columns;
		}
		
		public function create($tipos_menus) {
			$query = INSERT . WHITE_SPACE . INTO . WHITE_SPACE . TIPOS_MENUS . WHITE_SPACE . LEFT_PARENTHESES . TIPO_MENU . COMMA . WHITE_SPACE . CADASTRADO . COMMA . WHITE_SPACE . MODIFICADO . RIGHT_PARENTHESES . WHITE_SPACE . VALUES . WHITE_SPACE . LEFT_PARENTHESES . DOUBLE_QUOTES . $tipos_menus->getTipo_menu() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $tipos_menus->getCadastrado() . DOUBLE_QUOTES . COMMA . WHITE_SPACE . DOUBLE_QUOTES . $tipos_menus->getModificado() . DOUBLE_QUOTES . RIGHT_PARENTHESES;
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function read($where, $order, $hasPagination) {
			$count = NUMBER_ZERO;
			if ($where != STRING_EMPTY) {
				$where = WHERE . WHITE_SPACE . $where;
			}
			if ($order != STRING_EMPTY) {
				$order = ORDER_BY . WHITE_SPACE . $order;
			}
			$query = SELECT . WHITE_SPACE . $this->columns . WHITE_SPACE . FROM . WHITE_SPACE . TIPOS_MENUS . WHITE_SPACE . TIPOS_MENUS . WHITE_SPACE . $where;
			$this->setLog($query . WHITE_SPACE . $order);
			$result = $this->connection->execute($query . WHITE_SPACE . $order);
			$tipos_menusList = array();
			while ($row = $result->fetch_assoc()) {
				$tipos_menus = new model\Tipos_menus();
				$tipos_menus->setId($row[TIPOS_MENUS . POINT . ID]);
				$tipos_menus->setTipo_menu($row[TIPOS_MENUS . POINT . TIPO_MENU]);
				$tipos_menus->setCadastrado($row[TIPOS_MENUS . POINT . CADASTRADO]);
				$tipos_menus->setModificado($row[TIPOS_MENUS . POINT . MODIFICADO]);
				$tipos_menusList[$count] = $tipos_menus;
				$count++;
			}
			$this->connection->free($result);
			if ($hasPagination && $count > NUMBER_ZERO) {
				$result = $this->connection->execute($query);
				$size = NUMBER_ZERO;
				while ($row = $result->fetch_assoc()) {
					$size++;
				}
				$this->connection->free($result);				
				$this->size = $size;
			}
			return $tipos_menusList;
		}

		public function update($tipos_menus) {
			$query = UPDATE . WHITE_SPACE . TIPOS_MENUS . WHITE_SPACE . SET . WHITE_SPACE . ID . WHITE_SPACE . EQUALS . 
					WHITE_SPACE . DOUBLE_QUOTES . $tipos_menus->getId() . DOUBLE_QUOTES;
			if (!is_null($tipos_menus->getTipo_menu()) && !empty($tipos_menus->getTipo_menu())) {
				$query .= COMMA . WHITE_SPACE . TIPO_MENU . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
						$tipos_menus->getTipo_menu() . DOUBLE_QUOTES;
			}
			$query .= COMMA . WHITE_SPACE . MODIFICADO . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
					$tipos_menus->getModificado() . DOUBLE_QUOTES . WHITE_SPACE . WHERE . WHITE_SPACE . ID . EQUALS . 
					$tipos_menus->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

		public function delete($tipos_menus) {
			$query = DELETE . WHITE_SPACE . FROM . WHITE_SPACE . TIPOS_MENUS . WHITE_SPACE . WHERE . WHITE_SPACE . ID . 
					WHITE_SPACE . EQUALS . WHITE_SPACE . $tipos_menus->getId();
			$this->setLog($query);
			return $this->connection->execute($query);
		}

	}

?>