<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class Tipos_coresOutput implements \JsonSerializable {
			
		private $id;
		private $tipo_cor;
		private $cadastrado;
		private $modificado;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getTipo_cor() {
			return $this->tipo_cor;
		}
		
		public function setTipo_cor($tipo_cor) {
			$this->tipo_cor = $tipo_cor;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}

		public function getOutput($tipos_cores) {
			if (!is_null($tipos_cores)) {
				$tipos_coresOutput = new model\Tipos_coresOutput();
				$tipos_coresOutput->setId($tipos_cores->getId());
				$tipos_coresOutput->setTipo_cor($tipos_cores->getTipo_cor());
				return $tipos_coresOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($tipos_coresList) {
			$tipos_coresOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($tipos_coresList); $x++) {
				$tipos_coresOutputList[$count] = $this->getOutput($tipos_coresList[$x]);
				$count++;
			}
			return $tipos_coresOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>