<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class Tipos_permissoesOutput implements \JsonSerializable {
			
		private $id;
		private $tipo_permissao;
		private $cadastrado;
		private $modificado;
		private $coresOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getTipo_permissao() {
			return $this->tipo_permissao;
		}
		
		public function setTipo_permissao($tipo_permissao) {
			$this->tipo_permissao = $tipo_permissao;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getCoresOutput() {
			return $this->coresOutput;
		}
		
		public function setCoresOutput($coresOutput) {
			$this->coresOutput = $coresOutput;
		}

		public function getOutput($tipos_permissoes) {
			if (!is_null($tipos_permissoes)) {
				$tipos_permissoesOutput = new model\Tipos_permissoesOutput();
				$tipos_permissoesOutput->setId($tipos_permissoes->getId());
				$tipos_permissoesOutput->setTipo_permissao($tipos_permissoes->getTipo_permissao());
				$coresOutput = new model\CoresOutput();
				$tipos_permissoesOutput->setCoresOutput($coresOutput->getOutput($tipos_permissoes->getCores()));
				return $tipos_permissoesOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($tipos_permissoesList) {
			$tipos_permissoesOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($tipos_permissoesList); $x++) {
				$tipos_permissoesOutputList[$count] = $this->getOutput($tipos_permissoesList[$x]);
				$count++;
			}
			return $tipos_permissoesOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>