<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class Tipos_menusOutput implements \JsonSerializable {
			
		private $id;
		private $tipo_menu;
		private $cadastrado;
		private $modificado;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getTipo_menu() {
			return $this->tipo_menu;
		}
		
		public function setTipo_menu($tipo_menu) {
			$this->tipo_menu = $tipo_menu;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}

		public function getOutput($tipos_menus) {
			if (!is_null($tipos_menus)) {
				$tipos_menusOutput = new model\Tipos_menusOutput();
				$tipos_menusOutput->setId($tipos_menus->getId());
				$tipos_menusOutput->setTipo_menu($tipos_menus->getTipo_menu());
				return $tipos_menusOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($tipos_menusList) {
			$tipos_menusOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($tipos_menusList); $x++) {
				$tipos_menusOutputList[$count] = $this->getOutput($tipos_menusList[$x]);
				$count++;
			}
			return $tipos_menusOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>