<?php 
			
	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0	
	 */
	 
	namespace src\model; 
	use src\model;	

	class UsuariosOutput implements \JsonSerializable {
			
		private $id;
		private $usuario;
		private $cpf;
		private $email;
		private $senha;
		private $foto;
		private $access_token;
		private $access_token_expiration;
		private $password_token;
		private $password_token_expiration;
		private $activation_token;
		private $activation_token_expiration;
		private $cadastrado;
		private $modificado;
		private $situacoes_registrosOutput;
		private $perfisOutput;
			
		public function __construct() { }
					
		public function getId() {
			return $this->id;
		}
		
		public function setId($id) {
			$this->id = $id;
		}
					
		public function getUsuario() {
			return $this->usuario;
		}
		
		public function setUsuario($usuario) {
			$this->usuario = $usuario;
		}
					
		public function getCpf() {
			return $this->cpf;
		}
		
		public function setCpf($cpf) {
			$this->cpf = $cpf;
		}
					
		public function getEmail() {
			return $this->email;
		}
		
		public function setEmail($email) {
			$this->email = $email;
		}
					
		public function getSenha() {
			return $this->senha;
		}
		
		public function setSenha($senha) {
			$this->senha = $senha;
		}
					
		public function getFoto() {
			return $this->foto;
		}
		
		public function setFoto($foto) {
			$this->foto = $foto;
		}
					
		public function getAccess_token() {
			return $this->access_token;
		}
		
		public function setAccess_token($access_token) {
			$this->access_token = $access_token;
		}
					
		public function getAccess_token_expiration() {
			return $this->access_token_expiration;
		}
		
		public function setAccess_token_expiration($access_token_expiration) {
			$this->access_token_expiration = $access_token_expiration;
		}
					
		public function getPassword_token() {
			return $this->password_token;
		}
		
		public function setPassword_token($password_token) {
			$this->password_token = $password_token;
		}
					
		public function getPassword_token_expiration() {
			return $this->password_token_expiration;
		}
		
		public function setPassword_token_expiration($password_token_expiration) {
			$this->password_token_expiration = $password_token_expiration;
		}
					
		public function getActivation_token() {
			return $this->activation_token;
		}
		
		public function setActivation_token($activation_token) {
			$this->activation_token = $activation_token;
		}
					
		public function getActivation_token_expiration() {
			return $this->activation_token_expiration;
		}
		
		public function setActivation_token_expiration($activation_token_expiration) {
			$this->activation_token_expiration = $activation_token_expiration;
		}
					
		public function getCadastrado() {
			return $this->cadastrado;
		}
		
		public function setCadastrado($cadastrado) {
			$this->cadastrado = $cadastrado;
		}
					
		public function getModificado() {
			return $this->modificado;
		}
		
		public function setModificado($modificado) {
			$this->modificado = $modificado;
		}
					
		public function getSituacoes_registrosOutput() {
			return $this->situacoes_registrosOutput;
		}
		
		public function setSituacoes_registrosOutput($situacoes_registrosOutput) {
			$this->situacoes_registrosOutput = $situacoes_registrosOutput;
		}
					
		public function getPerfisOutput() {
			return $this->perfisOutput;
		}
		
		public function setPerfisOutput($perfisOutput) {
			$this->perfisOutput = $perfisOutput;
		}

		public function getOutput($usuarios) {
			if (!is_null($usuarios)) {
				$usuariosOutput = new model\UsuariosOutput();
				$usuariosOutput->setId($usuarios->getId());
				$usuariosOutput->setUsuario($usuarios->getUsuario());
				$usuariosOutput->setCpf($usuarios->getCpf());
				$usuariosOutput->setEmail($usuarios->getEmail());
				$usuariosOutput->setSenha($usuarios->getSenha());
				$usuariosOutput->setFoto($usuarios->getFoto());
				$usuariosOutput->setAccess_token($usuarios->getAccess_token());
				$usuariosOutput->setAccess_token_expiration($usuarios->getAccess_token_expiration());
				$usuariosOutput->setPassword_token($usuarios->getPassword_token());
				$usuariosOutput->setPassword_token_expiration($usuarios->getPassword_token_expiration());
				$usuariosOutput->setActivation_token($usuarios->getActivation_token());
				$usuariosOutput->setActivation_token_expiration($usuarios->getActivation_token_expiration());
				$situacoes_registrosOutput = new model\Situacoes_registrosOutput();
				$usuariosOutput->setSituacoes_registrosOutput($situacoes_registrosOutput->getOutput($usuarios->getSituacoes_registros()));
				$perfisOutput = new model\PerfisOutput();
				$usuariosOutput->setPerfisOutput($perfisOutput->getOutput($usuarios->getPerfis()));
				return $usuariosOutput;
			} else {
				return null;
			}
		}
			
		public function getOutputList($usuariosList) {
			$usuariosOutputList = array();
			$count = NUMBER_ZERO;
			for ($x = NUMBER_ZERO; $x < sizeof($usuariosList); $x++) {
				$usuariosOutputList[$count] = $this->getOutput($usuariosList[$x]);
				$count++;
			}
			return $usuariosOutputList;
		}
		
		public function jsonSerialize() {
			$objectVars = get_object_vars($this);
			return array_filter($objectVars, function ($value) { 
				return $value != null;
			});
		}		
		
	}
	
?>