<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Cores extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$coresInput = new model\CoresInput($this->request);
				if ($coresInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$coresDao = $this->daoFactory->getCoresDao();
					$result = $coresDao->create($coresInput->getEntity());
					$this->log->write(POST, $coresDao->getLog(), $this->debug);
					$insertId = $coresDao->getInsertId();
					if ($result) {		
						$coresList = $coresDao->read(CORES . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $coresDao->getLog(), $this->debug);
						$coresOutput = new model\CoresOutput();
						$this->response[RESPONSE][CORES][VALUE] = $coresOutput->getOutputList(
								$coresList);									
						$this->response[RESPONSE][CORES][SIZE] = sizeOf(
								$this->response[RESPONSE][CORES][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $coresInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = CORES . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = CORES . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$coresDao = $this->daoFactory->getCoresDao();
				$coresList = $coresDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $coresDao->getLog(), $this->debug);
				$coresOutput = new model\CoresOutput();
				$this->response[RESPONSE][CORES][VALUE] = $coresOutput->getOutputList($coresList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][CORES][SIZE] = $coresDao->getSize();
					if ($this->response[RESPONSE][CORES][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][CORES][SIZE] = sizeOf(
							$this->response[RESPONSE][CORES][VALUE]);	
					if ($this->response[RESPONSE][CORES][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$coresInput = new model\CoresInput($this->request);
					if ($coresInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$coresDao = $this->daoFactory->getCoresDao();
						$coresList = $coresDao->read(CORES . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $coresDao->getLog(), $this->debug);
						if (!is_null($coresList) && sizeOf($coresList) > NUMBER_ZERO) {
							$result = $coresDao->update($coresInput->getEntity());
							$this->log->write(PUT, $coresDao->getLog(), $this->debug);	
							if ($result) {	
								$coresList = $coresDao->read(CORES . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $coresDao->getLog(), $this->debug);
								$coresOutput = new model\CoresOutput();
								$this->response[RESPONSE][CORES][VALUE] = $coresOutput->getOutputList(
										$coresList);									
								$this->response[RESPONSE][CORES][SIZE] = sizeOf(
										$this->response[RESPONSE][CORES][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $coresInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$coresDao = $this->daoFactory->getCoresDao();
					$coresList = $coresDao->read(CORES . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $coresDao->getLog(), $this->debug);
					if (!is_null($coresList) && sizeOf($coresList) > NUMBER_ZERO) {
						$result = $coresDao->delete($coresList[NUMBER_ZERO]);
						$this->log->write(DELETE, $coresDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>