<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     http://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	
	namespace src\controller;
	use lib\getz;
	use src\logic;
	use src\model;
	use PHPMailer\PHPMailer\PHPMailer;	
	require "vendor/autoload.php";
	
	class Esqueci_a_minha_senha extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$esqueci_a_minha_senhaInput = new model\Esqueci_a_minha_senhaInput($this->request);
				if ($esqueci_a_minha_senhaInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$usuariosDao = $this->daoFactory->getUsuariosDao();
					$email = $esqueci_a_minha_senhaInput->getEmail();
					$where = USUARIOS . DOT . EMAIL . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . $email . 
							DOUBLE_QUOTES;
					$usuariosList = $usuariosDao->read($where , STRING_EMPTY, false);
					if (is_array($usuariosList) && sizeof($usuariosList) > NUMBER_ZERO) {
						$usuarios = $usuariosList[NUMBER_ZERO];
						$this->log->write(POST, $usuarios->getId(), $this->debug);
						$token = md5(uniqid(time())) . G3TZ . (($usuarios->getId() + NUMBER_THIRTY_TWO) * 
								NUMBER_ONE_HUNDRED_TWENTY_EIGHT);
						$usuarios->setPassword_token($token);
						$usuarios->setPassword_token_expiration(date(YMD_HIS, strtotime(MORE_ONE_DAYS)));
						$result = $usuariosDao->update($usuarios);
						$this->log->write(POST, $usuariosDao->getLog(), $this->debug);
						if ($result) {
							$tokenEncode = base64_encode($token);
							$mail = $this->sendForgotPasswordEmail($esqueci_a_minha_senhaInput->getEmail(), $tokenEncode);
							if ($mail) {
								$this->daoFactory->commit();
								$usuariosOutput = new model\UsuariosOutput();
								$usuariosOutput->setPassword_token($tokenEncode);
								$usuariosOutput->setPassword_token_expiration($usuarios->getPassword_token_expiration());
								$this->response[RESPONSE][USUARIOS][VALUE] = $usuariosOutput;
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;	
							} else {
								$this->daoFactory->rollback();	
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
							}
						} else {
							$this->daoFactory->rollback();	
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = FALHA_AO_ENCONTRAR_O_EMAIL;
					}
					$this->daoFactory->close();				
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $usuariosInput->getError();
				}
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}

		private function sendForgotPasswordEmail($mailTo, $tokenEncode) {
			$link = BASE_LINK . "/alterar_a_minha_senha/" . $tokenEncode;		
			$message = "<body style=\"margin: 0; padding: 0;\">
					<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" bgcolor=\"#eeeeee\">	
						<tr>
							<td style=\"padding: 32px 0;\">
								<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" style=\"border-collapse: collapse;\">
									<tr>
										<td align=\"center\" bgcolor=\"#12295d\" style=\"padding: 32px 32px; color: #ffffff; border-collapse: collapse; font-size: 28px; font-weight: bold; font-family: Arial, sans-serif;\">
											<b>@_YOUR_PROJECT</b>
										</td>
									</tr>
									<tr>
										<td bgcolor=\"#ffffff\" style=\"padding: 32px 32px;\">
											<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">
												<tr>
													<td style=\"color: #12295d; font-family: Arial, sans-serif; font-size: 24px;\">
														<b>Alterar a minha senha</b>
													</td>
												</tr>
												<tr>
													<td style=\"padding: 32px 0 0 0; color: #12295d; font-family: Arial, sans-serif; font-size: 16px; line-height: 20px;\">
														<p>Prezado usuário,</p>
														<p>Clique no link abaixo para alterar a sua senha.</p>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td bgcolor=\"#12295d\" style=\"padding: 32px 32px;\">
											<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">
												<tr>
													<td style=\"font-family: Arial, sans-serif; font-size: 16px; line-height: 20px;\">
														<a href=\"" . $link . "\"><font color=\"#ffffff\">" . $link . "</font></a>
													</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td bgcolor=\"#ffffff\" style=\"padding: 32px 32px;\">
											<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">
												<tr>
													<td style=\"padding: 0 0; color: #12295d; font-family: Arial, sans-serif; font-size: 14px; line-height: 20px;\">
														Este é um e-mail automático, por favor, não responda a este e-mail.
													</td>
												</tr>
											</table>
										</td>
									</tr>
									<tr>
										<td bgcolor=\"#ffffff\" style=\"padding: 32px 32px 32px 32px;\">
											<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">
												<tr>
													<td style=\"padding: 0 0; font-family: Arial, sans-serif; font-size: 14px; line-height: 20px; text-align: right;\">
														<a href=\"https://www.@_YOUR_PROJECT.com.br/@_YOUR_PROJECT\"><font color=\"#12295d\">@_YOUR_PROJECT</font></a>
													</td>
												</tr>
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</body>";
			$mail = new PHPMailer;
			$mail->isSMTP();
			$mail->SMTPDebug = 0;
			$mail->Host = "smtp.hostinger.com";
			$mail->Port = 587;
			$mail->SMTPAuth = true;
			$mail->Username = "noreply@@_YOUR_PROJECT.com.br";
			$mail->Password = "@_YOUR_PASSWORD";
			$mail->setFrom("noreply@@_YOUR_PROJECT.com.br", "@_YOUR_PROJECT");
			$mail->addReplyTo("noreply@@_YOUR_PROJECT.com.br", "@_YOUR_PROJECT");
			$mail->addAddress($mailTo);
			$mail->Subject = "@_YOUR_PROJECT - Alterar a minha senha";
			$mail->CharSet = "UTF-8";
			$mail->msgHTML($message);
			if ($mail->send()) {
				return true;
			} else {
				return false;
			}
		}
	}
	
?>