<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     http://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\logic;
	use src\model;
	
	class Image extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			// reset($_FILES);
			$temp = current($_FILES);
			if (is_uploaded_file($temp["tmp_name"])) {
				$path_info = pathinfo($temp["name"]);
				$file_name = md5(uniqid(time())) . "." . $path_info["extension"];
				move_uploaded_file($temp['tmp_name'], str_replace("@_YOUR_PROJECT-api", "@_YOUR_PROJECT", 
						$this->documentRoot) . "/res/doc/" . $file_name);
				$protocol = isset($_SERVER["HTTPS"]) && $_SERVER['HTTPS'] == "on" ? "https://" : "http://";
				$baseurl = $protocol . $_SERVER["HTTP_HOST"] . rtrim(dirname($_SERVER["REQUEST_URI"]), "/") . "/";
				echo json_encode(array("location" => str_replace("@_YOUR_PROJECT-api/api/", "@_YOUR_PROJECT/res/doc/", 
						$baseurl) . $file_name));
			}
		}
		
	}

?>