<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Menus extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$menusInput = new model\MenusInput($this->request);
				if ($menusInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$menusDao = $this->daoFactory->getMenusDao();
					$result = $menusDao->create($menusInput->getEntity());
					$this->log->write(POST, $menusDao->getLog(), $this->debug);
					$insertId = $menusDao->getInsertId();
					if ($result) {		
						$menusList = $menusDao->read(MENUS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $menusDao->getLog(), $this->debug);
						$menusOutput = new model\MenusOutput();
						$this->response[RESPONSE][MENUS][VALUE] = $menusOutput->getOutputList(
								$menusList);									
						$this->response[RESPONSE][MENUS][SIZE] = sizeOf(
								$this->response[RESPONSE][MENUS][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $menusInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = MENUS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = MENUS . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$menusDao = $this->daoFactory->getMenusDao();
				$menusList = $menusDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $menusDao->getLog(), $this->debug);
				$menusOutput = new model\MenusOutput();
				$this->response[RESPONSE][MENUS][VALUE] = $menusOutput->getOutputList($menusList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][MENUS][SIZE] = $menusDao->getSize();
					if ($this->response[RESPONSE][MENUS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][MENUS][SIZE] = sizeOf(
							$this->response[RESPONSE][MENUS][VALUE]);	
					if ($this->response[RESPONSE][MENUS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$menusInput = new model\MenusInput($this->request);
					if ($menusInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$menusDao = $this->daoFactory->getMenusDao();
						$menusList = $menusDao->read(MENUS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $menusDao->getLog(), $this->debug);
						if (!is_null($menusList) && sizeOf($menusList) > NUMBER_ZERO) {
							$result = $menusDao->update($menusInput->getEntity());
							$this->log->write(PUT, $menusDao->getLog(), $this->debug);	
							if ($result) {	
								$menusList = $menusDao->read(MENUS . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $menusDao->getLog(), $this->debug);
								$menusOutput = new model\MenusOutput();
								$this->response[RESPONSE][MENUS][VALUE] = $menusOutput->getOutputList(
										$menusList);									
								$this->response[RESPONSE][MENUS][SIZE] = sizeOf(
										$this->response[RESPONSE][MENUS][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $menusInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$menusDao = $this->daoFactory->getMenusDao();
					$menusList = $menusDao->read(MENUS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $menusDao->getLog(), $this->debug);
					if (!is_null($menusList) && sizeOf($menusList) > NUMBER_ZERO) {
						$result = $menusDao->delete($menusList[NUMBER_ZERO]);
						$this->log->write(DELETE, $menusDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>