<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Menu_submenus extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$menu_submenusInput = new model\Menu_submenusInput($this->request);
				if ($menu_submenusInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$menu_submenusDao = $this->daoFactory->getMenu_submenusDao();
					$result = $menu_submenusDao->create($menu_submenusInput->getEntity());
					$this->log->write(POST, $menu_submenusDao->getLog(), $this->debug);
					$insertId = $menu_submenusDao->getInsertId();
					if ($result) {		
						$menu_submenusList = $menu_submenusDao->read(MENU_SUBMENUS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $menu_submenusDao->getLog(), $this->debug);
						$menu_submenusOutput = new model\Menu_submenusOutput();
						$this->response[RESPONSE][MENU_SUBMENUS][VALUE] = $menu_submenusOutput->getOutputList(
								$menu_submenusList);									
						$this->response[RESPONSE][MENU_SUBMENUS][SIZE] = sizeOf(
								$this->response[RESPONSE][MENU_SUBMENUS][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $menu_submenusInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = MENU_SUBMENUS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = MENU_SUBMENUS . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$menu_submenusDao = $this->daoFactory->getMenu_submenusDao();
				$menu_submenusList = $menu_submenusDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $menu_submenusDao->getLog(), $this->debug);
				$menu_submenusOutput = new model\Menu_submenusOutput();
				$this->response[RESPONSE][MENU_SUBMENUS][VALUE] = $menu_submenusOutput->getOutputList($menu_submenusList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][MENU_SUBMENUS][SIZE] = $menu_submenusDao->getSize();
					if ($this->response[RESPONSE][MENU_SUBMENUS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][MENU_SUBMENUS][SIZE] = sizeOf(
							$this->response[RESPONSE][MENU_SUBMENUS][VALUE]);	
					if ($this->response[RESPONSE][MENU_SUBMENUS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$menu_submenusInput = new model\Menu_submenusInput($this->request);
					if ($menu_submenusInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$menu_submenusDao = $this->daoFactory->getMenu_submenusDao();
						$menu_submenusList = $menu_submenusDao->read(MENU_SUBMENUS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $menu_submenusDao->getLog(), $this->debug);
						if (!is_null($menu_submenusList) && sizeOf($menu_submenusList) > NUMBER_ZERO) {
							$result = $menu_submenusDao->update($menu_submenusInput->getEntity());
							$this->log->write(PUT, $menu_submenusDao->getLog(), $this->debug);	
							if ($result) {	
								$menu_submenusList = $menu_submenusDao->read(MENU_SUBMENUS . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $menu_submenusDao->getLog(), $this->debug);
								$menu_submenusOutput = new model\Menu_submenusOutput();
								$this->response[RESPONSE][MENU_SUBMENUS][VALUE] = $menu_submenusOutput->getOutputList(
										$menu_submenusList);									
								$this->response[RESPONSE][MENU_SUBMENUS][SIZE] = sizeOf(
										$this->response[RESPONSE][MENU_SUBMENUS][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $menu_submenusInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$menu_submenusDao = $this->daoFactory->getMenu_submenusDao();
					$menu_submenusList = $menu_submenusDao->read(MENU_SUBMENUS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $menu_submenusDao->getLog(), $this->debug);
					if (!is_null($menu_submenusList) && sizeOf($menu_submenusList) > NUMBER_ZERO) {
						$result = $menu_submenusDao->delete($menu_submenusList[NUMBER_ZERO]);
						$this->log->write(DELETE, $menu_submenusDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>