<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\model;
	
	class Perfis extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(POST)) {
				$perfisInput = new model\PerfisInput($this->request);
				if ($perfisInput->isValid(POST)) {
					$this->daoFactory->beginTransaction();
					$perfisDao = $this->daoFactory->getPerfisDao();
					$result = $perfisDao->create($perfisInput->getEntity());
					$this->log->write(POST, $perfisDao->getLog(), $this->debug);
					$insertId = $perfisDao->getInsertId();
					if ($result) {		
						$perfisList = $perfisDao->read(PERFIS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $insertId, STRING_EMPTY, false);
						$this->log->write(GET, $perfisDao->getLog(), $this->debug);
						$perfisOutput = new model\PerfisOutput();
						$this->response[RESPONSE][PERFIS][VALUE] = $perfisOutput->getOutputList(
								$perfisList);									
						$this->response[RESPONSE][PERFIS][SIZE] = sizeOf(
								$this->response[RESPONSE][PERFIS][VALUE]);							
						$this->daoFactory->commit();
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = SUCCESS;								
					} else {												
						$this->daoFactory->rollback();								
						$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
					}
					$this->daoFactory->close();					
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = $perfisInput->getError();
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				if ($this->resource != STRING_EMPTY) {
					$this->where = PERFIS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . $this->resource;	
				}
				if ($this->order == STRING_EMPTY) {
					$this->order = PERFIS . DOT . ID . WHITE_SPACE . DESC;
				}
				$this->daoFactory->beginTransaction();
				$perfisDao = $this->daoFactory->getPerfisDao();
				$perfisList = $perfisDao->read($this->where, $this->order, $this->hasPagination);	
				$this->log->write(GET, $perfisDao->getLog(), $this->debug);
				$perfisOutput = new model\PerfisOutput();
				$this->response[RESPONSE][PERFIS][VALUE] = $perfisOutput->getOutputList($perfisList);													
				$this->daoFactory->close();				
				if ($this->hasPagination) {
					$this->response[RESPONSE][PERFIS][SIZE] = $perfisDao->getSize();
					if ($this->response[RESPONSE][PERFIS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				} else {
					$this->response[RESPONSE][PERFIS][SIZE] = sizeOf(
							$this->response[RESPONSE][PERFIS][VALUE]);	
					if ($this->response[RESPONSE][PERFIS][SIZE] == NUMBER_ZERO) {
						$this->response[RESPONSE] = null;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;
					}
				}
				$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(PUT)) {		
				if ($this->resource != STRING_EMPTY && !empty($this->request) && $this->request[ID] == 
						$this->resource) {
					$perfisInput = new model\PerfisInput($this->request);
					if ($perfisInput->isValid(PUT)) {
						$this->daoFactory->beginTransaction();
						$perfisDao = $this->daoFactory->getPerfisDao();
						$perfisList = $perfisDao->read(PERFIS . DOT . ID . WHITE_SPACE . EQUALS . 
								WHITE_SPACE . $this->resource, STRING_EMPTY, false);
						$this->log->write(GET, $perfisDao->getLog(), $this->debug);
						if (!is_null($perfisList) && sizeOf($perfisList) > NUMBER_ZERO) {
							$result = $perfisDao->update($perfisInput->getEntity());
							$this->log->write(PUT, $perfisDao->getLog(), $this->debug);	
							if ($result) {	
								$perfisList = $perfisDao->read(PERFIS . DOT . ID . WHITE_SPACE . EQUALS . 
										WHITE_SPACE . $this->resource, STRING_EMPTY, false);
								$this->log->write(GET, $perfisDao->getLog(), $this->debug);
								$perfisOutput = new model\PerfisOutput();
								$this->response[RESPONSE][PERFIS][VALUE] = $perfisOutput->getOutputList(
										$perfisList);									
								$this->response[RESPONSE][PERFIS][SIZE] = sizeOf(
										$this->response[RESPONSE][PERFIS][VALUE]);							
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;									
							} else {							
								$this->daoFactory->rollback();
								$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;
							}
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
						}
						$this->daoFactory->close();
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = $perfisInput->getError();
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}
			} else if ($_SERVER[REQUEST_METHOD] == strtoupper(DELETE)) {
				if ($this->resource != STRING_EMPTY) {
					$this->daoFactory->beginTransaction();
					$perfisDao = $this->daoFactory->getPerfisDao();
					$perfisList = $perfisDao->read(PERFIS . DOT . ID . WHITE_SPACE . EQUALS . WHITE_SPACE . 
							$this->resource, STRING_EMPTY, false);
					$this->log->write(GET, $perfisDao->getLog(), $this->debug);
					if (!is_null($perfisList) && sizeOf($perfisList) > NUMBER_ZERO) {
						$result = $perfisDao->delete($perfisList[NUMBER_ZERO]);
						$this->log->write(DELETE, $perfisDao->getLog(), $this->debug);	
						if ($result) {
							$this->daoFactory->commit();
							$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = SUCCESS;							
						} else {
							$this->daoFactory->rollback();
							$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
						}
						$this->daoFactory->close();	
					} else {
						$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
						$this->response[RESPONSE][MESSAGE] = DATA_NOT_FOUND;	
					}
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
				}				
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>