<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     http://outcicle.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	
	namespace src\controller;
	use lib\getz;
	use src\model;
	use PHPMailer\PHPMailer\PHPMailer;
	
	class Send extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				$isSend = $this->send();
				if ($isSend) {
					$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = SUCCESS;
				} else {
					$this->response[RESPONSE][STATUS] = NUMBER_FIVE_HUNDRED;
					$this->response[RESPONSE][MESSAGE] = INTERNAL_SERVER_ERROR;	
				}
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;	
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}

		private function send() {
			$message = "<body style=\"margin: 0; padding: 0;\">
					<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" bgcolor=\"#eeeeee\">	
						<tr>
							<td style=\"padding: 32px 0;\">
								<table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\" style=\"border-collapse: collapse;\">
									<tr>
										<td bgcolor=\"#ffffff\" style=\"padding: 32px 32px;\">
											<table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\">
												<tr>
													<td style=\"color: #000000; font-family: Arial, sans-serif; font-size: 24px;\">
														<b>Hello, world!</b>
													</td>
												</tr>
											</table>
										</td>
									</tr>
								</table>
							</td>
						</tr>
					</table>
				</body>";
			$mail = new PHPMailer;
			$mail->isSMTP();
			$mail->SMTPDebug = 0; // use 2 for advanced debug
			$mail->Host = "@_YOUR_SMTP";
			$mail->Port = @_YOUR_PORT;
			$mail->SMTPAuth = true;
			$mail->Username = "@_YOUR_USERNAME";
			$mail->Password = "@_YOUR_PASSWORD";
			$mail->setFrom("@_YOUR_EMAIL", "@_YOUR_PROJECT");
			$mail->addReplyTo("@_YOUR_EMAIL", "@_YOUR_PROJECT");
			$mail->addAddress("@_YOUR_DESTINATION");
			$mail->Subject = "@_YOUR_PROJECT";
			$mail->CharSet = "UTF-8";
			$mail->msgHTML($message);
			if ($mail->send()) {
				return true;
			} else {
				return false;
			}
		}
	}
?>