<?php

	/**
	 * Generated by Getz Framework.
	 * 
	 * @author  Mario Sakamoto <mskamot@gmail.com>
	 * @see     https://wtag.com.br/getz
	 * @since   1.0.0
	 * @version 1.0.0
	 */
	 
	namespace src\controller;
	use lib\getz;
	use src\logic;
	use src\model;
	
	class User extends getz\Activator {
		
		public function __construct() { }
		
		public function init() {
			enableCORS();
			if ($_SERVER[REQUEST_METHOD] == strtoupper(GET)) {
				foreach (getallheaders() as $name => $value) {
					if ($name == AUTHORIZATION) {
						$authorization = new logic\Authorization($value);
						if ($authorization->isValid()) {
							$cpf = $authorization->getToken()->getCpf();	
							$where = USUARIOS . DOT . CPF . WHITE_SPACE . EQUALS . WHITE_SPACE . DOUBLE_QUOTES . 
									$cpf . DOUBLE_QUOTES . WHITE_SPACE . STRING_AND . WHITE_SPACE . USUARIOS . 
									DOT . SITUACAO_REGISTRO . WHITE_SPACE . EQUALS . WHITE_SPACE . NUMBER_ONE;
							$this->daoFactory->beginTransaction();
							$usuariosDao = $this->daoFactory->getUsuariosDao();
							$usuariosList = $usuariosDao->read($where, STRING_EMPTY, false);	
							if (is_array($usuariosList) && sizeof($usuariosList) > NUMBER_ZERO) {		
								$this->response[RESPONSE][USUARIOS][VALUE][NUMBER_ZERO] = $authorization->getToken();						
								$this->daoFactory->commit();
								$this->response[RESPONSE][STATUS] = NUMBER_TWO_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = SUCCESS;								
							} else {
								$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
								$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;
							}
							$this->daoFactory->close();							
						} else {
							$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
							$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;
						}
					}
				}
			} else {
				$this->response[RESPONSE][STATUS] = NUMBER_FOUR_HUNDRED;
				$this->response[RESPONSE][MESSAGE] = BAD_REQUEST;
			}
			echo json_encode($this->response, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
		}
		
	}

?>